/**
 * Deck templates: curated combinations of theme + font + graphic + per-layout
 * variants + a sample prompt. Picking a template skips the theme/font/graphic
 * steps and jumps straight to "edit prompt and generate".
 *
 * Variant defaults are applied to every slide in the generated deck so the
 * whole deck inherits a cohesive visual language (e.g. "Editorial Sand" makes
 * every quote slide use the editorial pull-quote variant, every title-hero
 * use the underlined variant, etc.).
 */

import type { ContentDensity, Slide } from "./types";

export type TemplateVariantDefaults = {
  titleVariant?: Slide["titleVariant"];
  bulletsVariant?: Slide["bulletsVariant"];
  twoColumnVariant?: Slide["twoColumnVariant"];
  tableVariant?: Slide["tableVariant"];
  quoteVariant?: Slide["quoteVariant"];
  sectionVariant?: Slide["sectionVariant"];
  closingVariant?: Slide["closingVariant"];
};

export type DeckTemplate = {
  id: string;
  name: string;
  /** One-line description shown under the title. */
  tagline: string;
  /** Short label used as a chip (Pitch, Lecture, Report, etc.). */
  category: string;
  themeId: string;
  fontId: string;
  graphicId: string;
  /** Optional accent override for the graphic. */
  graphicAccent?: string;
  /** Generation defaults. */
  density?: ContentDensity;
  includeReferences?: boolean;
  /** Sample prompt seeded into the brief so the user can tweak it. */
  samplePrompt: string;
  /** Per-layout visual variants applied to every slide after generation. */
  variants: TemplateVariantDefaults;
  /** Show a "NEW" badge on the gallery card. */
  isNew?: boolean;
};

export const DECK_TEMPLATES: DeckTemplate[] = [
  /* ============================================================
   * REFERENCE-BUILT TITLE SETS — five title-slide designs matched
   * from real decks: grain sphere, classic editorial, display serif,
   * stacked bold profile, and centered serif. Each sets its own
   * title-hero variant so the cover reads exactly like the reference.
   * ============================================================ */
  {
    id: "crimson-grain",
    name: "Crimson Grain",
    tagline: "Bold left title, a red accent rule, and a soft grain sphere. Clean, premium pitch cover.",
    category: "Pitch",
    themeId: "blush-grain",
    fontId: "inter",
    graphicId: "none",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Investor pitch for a new product: the problem, our solution, traction, market, and the ask.",
    variants: {
      titleVariant: "grain-sphere",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
    isNew: true,
  },
  {
    id: "editorial-classic",
    name: "Editorial Classic",
    tagline: "A serif headline over a full-width rule with a tracked subtitle. Timeless and corporate.",
    category: "Editorial",
    themeId: "ink-paper",
    fontId: "playfair",
    graphicId: "none",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "A new business opportunity brief for the leadership team: context, the opportunity, the plan, and next steps.",
    variants: {
      titleVariant: "editorial-classic",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "contact",
    },
    isNew: true,
  },
  {
    id: "display-folio",
    name: "Display Folio",
    tagline: "A framed cover with a giant display-serif title between two rules. Editorial portfolio energy.",
    category: "Portfolio",
    themeId: "cream-noir",
    fontId: "fraunces",
    graphicId: "none",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "A creative portfolio overview: who I am, selected work, the process, results, and how to get in touch.",
    variants: {
      titleVariant: "display-serif",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "giant-mark",
      sectionVariant: "chapter",
      closingVariant: "signature",
    },
    isNew: true,
  },
  {
    id: "company-profile",
    name: "Company Profile",
    tagline: "A heavy uppercase title with a dashed rule and bold corner blocks. Confident business profile.",
    category: "Business",
    themeId: "crimson-blocks",
    fontId: "montserrat",
    graphicId: "none",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "A company profile: who we are, what we do, our services, our results, and how to reach us.",
    variants: {
      titleVariant: "stacked-bold",
      bulletsVariant: "icon-check",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "panel",
      closingVariant: "contact",
    },
    isNew: true,
  },
  {
    id: "group-serif",
    name: "Group Serif",
    tagline: "A symmetric cover with a serif-italic title framed by dot-and-line accents. Academic and calm.",
    category: "Academic",
    themeId: "navy-serif",
    fontId: "playfair",
    graphicId: "none",
    density: "balanced",
    includeReferences: true,
    samplePrompt: "A group project on enhancing product sales strategy: background, research, our proposal, and results.",
    variants: {
      titleVariant: "centered-serif",
      bulletsVariant: "numbered",
      twoColumnVariant: "classic",
      tableVariant: "zebra",
      quoteVariant: "centered",
      sectionVariant: "minimal",
      closingVariant: "centered",
    },
    isNew: true,
  },

  /* ============================================================
   * PREMIUM SET (Canva/Gamma-grade) — five fresh templates pairing
   * new palettes with new low-opacity textured backgrounds.
   * ============================================================ */
  {
    id: "aurora-nights",
    name: "Aurora Nights",
    tagline: "Deep indigo with an aurora glow and a whisper-fine dot grid. Premium, modern, dark.",
    category: "Keynote",
    themeId: "aurora-night",
    fontId: "space-grotesk",
    graphicId: "aurora-flow",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Product keynote for a new AI platform: the shift happening now, what we built, how it works, the proof, and where this goes next.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
    isNew: true,
  },
  {
    id: "peach-editorial",
    name: "Peach Editorial",
    tagline: "Warm peach cream, soft grain, a thin coral arc. Magazine-grade and calm.",
    category: "Editorial",
    themeId: "peach-cream",
    fontId: "fraunces",
    graphicId: "warm-grain",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "A long-form brand story for a boutique coffee roaster: origins, craft, the people, and what we stand for.",
    variants: {
      titleVariant: "editorial-serif",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
    isNew: true,
  },
  {
    id: "teal-depths",
    name: "Teal Depths",
    tagline: "Deep teal with mint glass circles and fine hatching. Confident, techy, fresh.",
    category: "Report",
    themeId: "deep-teal",
    fontId: "outfit",
    graphicId: "prism-glass",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Quarterly business review: headline metrics, what moved, what stalled, the plan for next quarter, and risks we're watching.",
    variants: {
      titleVariant: "numbered",
      bulletsVariant: "icon-check",
      twoColumnVariant: "compare",
      tableVariant: "zebra",
      quoteVariant: "card",
      sectionVariant: "panel",
      closingVariant: "contact",
    },
    isNew: true,
  },
  {
    id: "lilac-studio",
    name: "Lilac Studio",
    tagline: "Soft lilac mist with blurred blooms and a faint plus-grid. Friendly startup polish.",
    category: "Startup",
    themeId: "lilac-mist",
    fontId: "plus-jakarta",
    graphicId: "lilac-bloom",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Seed pitch for a wellness app: the problem, our approach, early traction, the market, and what we're raising.",
    variants: {
      titleVariant: "asymmetric",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "minimal",
      quoteVariant: "centered",
      sectionVariant: "split",
      closingVariant: "cta",
    },
    isNew: true,
  },
  {
    id: "graphite-gold",
    name: "Graphite Gold",
    tagline: "Graphite black framed in thin gold, with a quiet grid. Luxe, premium, brand-forward.",
    category: "Brand",
    themeId: "graphite-gold",
    fontId: "playfair",
    graphicId: "lux-frame",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "A luxury brand launch deck: the vision, the product, the craftsmanship, the experience, and the invitation.",
    variants: {
      titleVariant: "centered",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "bordered",
      quoteVariant: "giant-mark",
      sectionVariant: "chapter",
      closingVariant: "signature",
    },
    isNew: true,
  },

  {
    id: "concept-map",
    name: "Concept Map",
    tagline: "Playful rainbow numbered cards on soft lavender. Bright, friendly, and crystal clear.",
    category: "Creative",
    themeId: "bright-ideas",
    fontId: "poppins",
    graphicId: "none",
    density: "concise",
    includeReferences: false,
    samplePrompt: "An overview of our team's core ideas and initiatives — one short, punchy card per idea.",
    variants: {
      titleVariant: "concept-hero",
      bulletsVariant: "concept-cards",
      twoColumnVariant: "cards",
      tableVariant: "minimal",
      quoteVariant: "centered",
      sectionVariant: "minimal",
      closingVariant: "centered",
    },
    isNew: true,
  },

  /* ============================================================
   * SAGE & BLUSH — soft, organic, editorial. Pairs the
   * "organic-sage" graphic with a sage + blush theme and Fraunces.
   * ============================================================ */
  {
    id: "sage-blush",
    name: "Sage & Blush",
    tagline: "Soft organic shapes, sage and blush, gentle gold rings. Editorial calm.",
    category: "Editorial",
    themeId: "sage-blush",
    fontId: "fraunces",
    graphicId: "organic-sage",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "A reflective long-form essay on craftsmanship in software, written for a senior engineering audience.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
    isNew: true,
  },

  /* ============================================================
   * NEW HERO SET — six saturated, high-impact templates designed
   * to ship together. Bold backgrounds, bright contrasting accents,
   * white text everywhere so legibility is guaranteed across every
   * layout. These sit at the top of the catalog so they land on
   * the first page of the gallery.
   * ============================================================ */
  {
    id: "midnight-aurora",
    name: "Midnight Aurora",
    tagline: "Deep slate with electric amber. Modern, premium, conference-stage.",
    category: "Keynote",
    themeId: "slate-bold",
    fontId: "bricolage",
    graphicId: "mesh-gradient",
    graphicAccent: "#F59E0B",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Annual product keynote: the year in review, what we shipped, the bet for the year ahead, and the one thing we want people to remember.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
    isNew: true,
  },
  {
    id: "neon-crimson",
    name: "Neon Crimson",
    tagline: "Saturated crimson with gold accents. Loud, confident, unmissable.",
    category: "Pitch",
    themeId: "crimson",
    fontId: "syne",
    graphicId: "diagonal-stripes",
    graphicAccent: "#FCD34D",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Series A pitch for a consumer fintech app. Problem, our edge, traction so far, market size, the team, the ask.",
    variants: {
      titleVariant: "asymmetric",
      bulletsVariant: "numbered",
      twoColumnVariant: "compare",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "split",
      closingVariant: "cta",
    },
    isNew: true,
  },
  {
    id: "electric-cobalt",
    name: "Electric Cobalt",
    tagline: "Cobalt blue with tangerine accents. Trustworthy, sharp, enterprise-grade.",
    category: "Investor",
    themeId: "cobalt",
    fontId: "ibm-plex-sans",
    graphicId: "concentric",
    graphicAccent: "#FB923C",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Quarterly investor update: ARR, retention, hiring, what shipped, what's blocked, and our ask for the next round.",
    variants: {
      titleVariant: "numbered",
      bulletsVariant: "icon-check",
      twoColumnVariant: "numbered",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "split",
      closingVariant: "contact",
    },
    isNew: true,
  },
  {
    id: "emerald-prism",
    name: "Emerald Prism",
    tagline: "Deep emerald with gold rays. Climate, sustainability, vision-forward.",
    category: "Keynote",
    themeId: "emerald",
    fontId: "manrope",
    graphicId: "topographic",
    graphicAccent: "#FCD34D",
    density: "balanced",
    includeReferences: true,
    samplePrompt: "Climate strategy keynote: where we are on emissions, the net-zero plan, the partners we need, and what success looks like in five years.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "icon-check",
      twoColumnVariant: "compare",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
    isNew: true,
  },
  {
    id: "royal-flux",
    name: "Royal Flux",
    tagline: "Royal indigo with hot-pink edge. Bold creative pitches and brand decks.",
    category: "Brand",
    themeId: "royal-indigo",
    fontId: "outfit",
    graphicId: "corner-arc",
    graphicAccent: "#F472B6",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Creative agency capabilities deck. Who we are, the work we love, our process, and the kinds of partners we want to build with.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
    isNew: true,
  },
  {
    id: "obsidian-edge",
    name: "Obsidian Edge",
    tagline: "Black canvas with violet accents. Engineering, security, deep tech.",
    category: "Engineering",
    themeId: "obsidian",
    fontId: "jetbrains",
    graphicId: "blueprint",
    graphicAccent: "#A78BFA",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Architecture review for our new payments service. Goals, the design, the alternatives we considered, the tradeoffs, the rollout plan.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "dashed",
      twoColumnVariant: "compare",
      tableVariant: "compact",
      quoteVariant: "card",
      sectionVariant: "minimal",
      closingVariant: "qa",
    },
    isNew: true,
  },

  /* ============================================================
   * Original catalog continues below.
   * ============================================================ */
  {
    id: "bold-cobalt",
    name: "Bold Cobalt",
    tagline: "Solid color, big confident type. Made for keynote-style decks.",
    category: "Keynote",
    themeId: "cobalt",
    fontId: "outfit",
    graphicId: "corner-blocks",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Company all-hands keynote covering Q3 results, the product bet for next year, and how the team is growing.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "numbered",
      twoColumnVariant: "numbered",
      tableVariant: "accent-header",
      quoteVariant: "centered",
      sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "crimson-hero",
    name: "Crimson Hero",
    tagline: "Dramatic red panels with editorial pacing.",
    category: "Pitch",
    themeId: "crimson",
    fontId: "bricolage",
    graphicId: "arch-corner",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Seed-stage pitch for a consumer app. Problem, insight, product, traction, the team, the ask.",
    variants: {
      titleVariant: "numbered",
      bulletsVariant: "icon-check",
      twoColumnVariant: "compare",
      tableVariant: "accent-header",
      quoteVariant: "editorial",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "editorial-sand",
    name: "Editorial Sand",
    tagline: "Magazine feel. Serif type, generous whitespace, quiet decoration.",
    category: "Editorial",
    themeId: "sand",
    fontId: "playfair",
    graphicId: "minimal-divider",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Long-form report on the future of remote work, written for a thoughtful business audience.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },
  {
    id: "tech-mono",
    name: "Tech Mono",
    tagline: "Mono type, blueprint grid. Engineering and product reviews.",
    category: "Engineering",
    themeId: "charcoal",
    fontId: "jetbrains",
    graphicId: "blueprint",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Engineering review of a payments service: architecture, SLOs, on-call pain, and what we ship next quarter.",
    variants: {
      titleVariant: "centered",
      bulletsVariant: "dashed",
      twoColumnVariant: "classic",
      tableVariant: "compact",
      quoteVariant: "card",
      sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "royal-indigo",
    name: "Royal Indigo",
    tagline: "Saturated indigo with gold accents. Big-stage confidence.",
    category: "Keynote",
    themeId: "royal-indigo",
    fontId: "space-grotesk",
    graphicId: "corner-arc",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Industry keynote on AI-native developer tools. Where we are, where it's going, what to build now.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "investor-navy",
    name: "Investor Navy",
    tagline: "Boardroom safe. Disciplined columns and clean tables.",
    category: "Investor",
    themeId: "corp-navy",
    fontId: "inter",
    graphicId: "side-bar",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Q1 investor update covering ARR growth, churn, hiring, and our ask for the next round.",
    variants: {
      titleVariant: "asymmetric",
      bulletsVariant: "numbered",
      twoColumnVariant: "numbered",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "mint-startup",
    name: "Mint Startup",
    tagline: "Friendly and modern. Soft mint with confident type.",
    category: "Startup",
    themeId: "mint-sage",
    fontId: "dm-sans",
    graphicId: "dot-field",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "B2B SaaS pitch for an expense automation tool. Problem, solution, traction, market, ask.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "minimal",
      quoteVariant: "card",
      sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "burgundy-edit",
    name: "Burgundy Editorial",
    tagline: "Wine-and-cream serif feel. Best for deep narrative pieces.",
    category: "Editorial",
    themeId: "burgundy",
    fontId: "fraunces",
    graphicId: "ribbon-stripe",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "A reflective talk on craftsmanship in software, written for a senior engineering audience.",
    variants: {
      titleVariant: "numbered",
      bulletsVariant: "dashed",
      twoColumnVariant: "divider",
      tableVariant: "minimal",
      quoteVariant: "editorial",
      sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "plum-bold",
    name: "Plum Bold",
    tagline: "Punchy purple, big numbers. Brand-forward decks.",
    category: "Brand",
    themeId: "plum",
    fontId: "syne",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand vision deck for a creative agency. Who we are, what we believe, work we love, who we want to work with.",
    variants: {
      titleVariant: "big-initial",
      bulletsVariant: "numbered",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "stacked",
      sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "forest-academic",
    name: "Forest Academic",
    tagline: "Quiet forest tones, classical serif. Lectures and research.",
    category: "Lecture",
    themeId: "forest-cream",
    fontId: "lora",
    graphicId: "topographic",
    density: "comprehensive",
    includeReferences: true,
    samplePrompt: "Undergraduate lecture on transformer architectures: attention, encoders, decoders, and a worked example.",
    variants: {
      titleVariant: "centered",
      bulletsVariant: "icon-check",
      twoColumnVariant: "classic",
      tableVariant: "minimal",
      quoteVariant: "card",
      sectionVariant: "chapter",
      closingVariant: "centered",
    },
  },
  {
    id: "tangerine-bold",
    name: "Tangerine Bold",
    tagline: "Solid tangerine. Marketing and creative kickoffs.",
    category: "Marketing",
    themeId: "tangerine",
    fontId: "archivo",
    graphicId: "corner-circles",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Marketing campaign brief for a Q4 holiday push. Audience, message, channels, KPIs, timeline.",
    variants: {
      titleVariant: "asymmetric",
      bulletsVariant: "cards",
      twoColumnVariant: "cards",
      tableVariant: "accent-header",
      quoteVariant: "card",
      sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "slate-bold",
    name: "Slate Bold",
    tagline: "Slate gray with amber accents. Strategy and ops decks.",
    category: "Strategy",
    themeId: "slate-bold",
    fontId: "plus-jakarta",
    graphicId: "editorial-grid",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Annual strategy review: where we won, where we lost, the bets we are doubling down on next year.",
    variants: {
      titleVariant: "underlined",
      bulletsVariant: "numbered",
      twoColumnVariant: "compare",
      tableVariant: "accent-header",
      quoteVariant: "editorial",
      sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },

  /* ----- additional templates: more variety, more vibes ----- */
  {
    id: "ivory-classic",
    name: "Ivory Classic",
    tagline: "Black serif on warm ivory. Quietly authoritative.",
    category: "Editorial",
    themeId: "ivory",
    fontId: "playfair",
    graphicId: "minimal-divider",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "An essay on the state of typography in 2026: where it is, where it's going, who's pushing it.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },
  {
    id: "ocean-pearl",
    name: "Ocean & Pearl",
    tagline: "Deep teal accents on pearl. Calm, professional, marine.",
    category: "Investor",
    themeId: "ocean-deep",
    fontId: "ibm-plex-sans",
    graphicId: "wave",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Series B raise deck for a logistics platform. Customers, growth, unit economics, the ask.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "bordered", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    tagline: "Warm copper on cream. Beauty, fashion, lifestyle brands.",
    category: "Brand",
    themeId: "rose-gold",
    fontId: "fraunces",
    graphicId: "arch-corner",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand book for a skincare startup. Vision, voice, principles, do's and don'ts.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "kicker-hero",
      closingVariant: "signature",
    },
  },
  {
    id: "emerald-power",
    name: "Emerald Power",
    tagline: "Saturated emerald with gold. Sustainability, climate, ESG.",
    category: "Keynote",
    themeId: "emerald",
    fontId: "manrope",
    graphicId: "topographic",
    density: "balanced",
    includeReferences: true,
    samplePrompt: "Climate strategy keynote: where we are on emissions, the targets, the path, the partners.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "icon-check", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "powder-rose",
    name: "Powder Rose",
    tagline: "Soft rose with rich crimson accents. Feminine, modern, friendly.",
    category: "Brand",
    themeId: "powder-rose",
    fontId: "outfit",
    graphicId: "corner-circles",
    density: "concise",
    includeReferences: false,
    samplePrompt: "Launch deck for a wellness app aimed at busy professionals. The why, the how, the first 90 days.",
    variants: {
      titleVariant: "centered", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    tagline: "Soft lavender with deep purple. Creative ops and design reviews.",
    category: "Brand",
    themeId: "lavender",
    fontId: "bricolage",
    graphicId: "mesh-gradient",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Design review for the new mobile onboarding flow. Goals, the journey, what tested well, what didn't.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "soft-indigo",
    name: "Soft Indigo",
    tagline: "Calm indigo wash. Onboarding decks and internal training.",
    category: "Training",
    themeId: "soft-indigo",
    fontId: "figtree",
    graphicId: "soft-grid",
    density: "comprehensive",
    includeReferences: false,
    samplePrompt: "Onboarding deck for new engineers. Tools, process, code review culture, who to ask for what.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "icon-check", twoColumnVariant: "classic",
      tableVariant: "zebra", quoteVariant: "centered", sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "halftone-print",
    name: "Halftone Print",
    tagline: "Newsprint halftone, editorial type. Magazine-style features.",
    category: "Editorial",
    themeId: "ivory",
    fontId: "merriweather",
    graphicId: "halftone",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Long-read essay on the rebirth of print magazines in a digital era.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "memphis-pop",
    name: "Memphis Pop",
    tagline: "Squiggles, dots, shapes. Playful, design-forward, attention-grabbing.",
    category: "Brand",
    themeId: "blue-white",
    fontId: "syne",
    graphicId: "memphis",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Pitch for a youth-oriented streaming platform. Vibes, audience, content strategy, the launch.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "bauhaus",
    name: "Bauhaus",
    tagline: "Geometric shapes, primary palette. Architecture and design firms.",
    category: "Brand",
    themeId: "ivory",
    fontId: "archivo",
    graphicId: "bauhaus",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Studio overview for an architecture firm. Philosophy, recent work, the team, what we are looking for.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "cards",
      tableVariant: "bordered", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "blueprint-eng",
    name: "Blueprint",
    tagline: "Drafting grid, technical type. Engineering RFCs and ADR walkthroughs.",
    category: "Engineering",
    themeId: "blue-white",
    fontId: "ibm-plex-sans",
    graphicId: "blueprint",
    density: "comprehensive",
    includeReferences: false,
    samplePrompt: "RFC review for migrating from Postgres to a sharded setup. Why, the design, tradeoffs, rollout.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "compare",
      tableVariant: "compact", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "dot-field",
    name: "Dot Field",
    tagline: "Atmospheric dots, soft fade. Data and AI products.",
    category: "Engineering",
    themeId: "fog",
    fontId: "space-grotesk",
    graphicId: "dot-field",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Technical deep-dive on our recommendation system: data, model, experiments, the next bet.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "classic",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "qa",
    },
  },
  {
    id: "concentric",
    name: "Concentric",
    tagline: "Quiet arcs in the corner. Boardroom-clean strategy decks.",
    category: "Strategy",
    themeId: "blue-white",
    fontId: "inter",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Three-year operating plan. Where we are, the bets, the milestones, what could go wrong.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "stripes-corp",
    name: "Diagonal Stripes",
    tagline: "Energetic diagonals, corporate restraint. Sales kickoffs.",
    category: "Sales",
    themeId: "red-white",
    fontId: "manrope",
    graphicId: "diagonal-stripes",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Sales kickoff for the new fiscal year. Targets, territories, plays, incentives.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "numbered", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "olive-academic",
    name: "Olive Academic",
    tagline: "Olive serif. Scholarly conferences and dissertations.",
    category: "Lecture",
    themeId: "olive",
    fontId: "source-serif",
    graphicId: "topographic",
    density: "comprehensive",
    includeReferences: true,
    samplePrompt: "Conference paper presentation: hypothesis, methodology, findings, limitations, future work.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "classic",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "chapter",
      closingVariant: "qa",
    },
  },
  {
    id: "sky-startup",
    name: "Sky Startup",
    tagline: "Open sky blues. Optimistic startup demos.",
    category: "Startup",
    themeId: "sky",
    fontId: "dm-sans",
    graphicId: "wave",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Demo day pitch for a developer tool that auto-generates database migrations.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "mosaic-creative",
    name: "Mosaic",
    tagline: "Colorful triangle mosaic. Workshop decks, creative kickoffs.",
    category: "Marketing",
    themeId: "purple-white",
    fontId: "outfit",
    graphicId: "mosaic",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand workshop kickoff. Discovery, ideation, sprints, deliverables, timeline.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "qa",
    },
  },
  {
    id: "mustard-zine",
    name: "Mustard Zine",
    tagline: "Mustard and ink with serif type. Zine-style storytelling.",
    category: "Editorial",
    themeId: "mustard",
    fontId: "fraunces",
    graphicId: "ribbon-stripe",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Field journal of a year-long product research project. The questions, what we found, what surprised us.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "coral-pop",
    name: "Coral Pop",
    tagline: "Solid coral with charcoal accents. Energetic launches.",
    category: "Marketing",
    themeId: "coral-solid",
    fontId: "syne",
    graphicId: "corner-blocks",
    density: "concise",
    includeReferences: false,
    samplePrompt: "Product launch deck: the problem, the leap, the ask, the timeline.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "clay-warm",
    name: "Clay & Cream",
    tagline: "Earthy clay with cream. Hospitality, food, lifestyle.",
    category: "Brand",
    themeId: "clay-cream",
    fontId: "lora",
    graphicId: "minimal-divider",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Restaurant concept deck: the cuisine, the room, the menu, the team, the build.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "minimal",
      closingVariant: "signature",
    },
  },
  {
    id: "quiet-blue",
    name: "Quiet Blue",
    tagline: "Subtle slate-blue. Polished internal updates.",
    category: "Investor",
    themeId: "quiet-blue",
    fontId: "inter",
    graphicId: "side-bar",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Monthly business review: revenue, retention, hiring, what shipped, what's next.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "contact",
    },
  },
  {
    id: "stripe-fashion",
    name: "Editorial Stripe",
    tagline: "Burgundy stripe, magazine pacing. Fashion lookbooks and runway notes.",
    category: "Editorial",
    themeId: "burgundy",
    fontId: "playfair",
    graphicId: "minimal-divider",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Lookbook walkthrough for a fall collection. Inspiration, silhouettes, palette, the show.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "editorial", sectionVariant: "kicker-hero",
      closingVariant: "signature",
    },
  },
  {
    id: "indigo-enterprise",
    name: "Indigo Enterprise",
    tagline: "Royal indigo, generous spacing. Enterprise sales decks.",
    category: "Sales",
    themeId: "royal-indigo",
    fontId: "ibm-plex-sans",
    graphicId: "side-bar",
    density: "detailed",
    includeReferences: false,
    samplePrompt: "Enterprise sales pitch for our security platform. Risks, our approach, deployment, references.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "icon-check", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "split-bold",
    name: "Split Bold",
    tagline: "Diagonal split, big numbers. Performance recaps.",
    category: "Strategy",
    themeId: "charcoal",
    fontId: "bricolage",
    graphicId: "split-diagonal",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Year-end recap. The numbers, the wins, the misses, what we learned, the next chapter.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "numbered", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "chapter",
      closingVariant: "signature",
    },
  },
  {
    id: "minimal-mono",
    name: "Minimal Mono",
    tagline: "All-mono type, ultra-minimal. Code reviews and post-mortems.",
    category: "Engineering",
    themeId: "ivory",
    fontId: "jetbrains",
    graphicId: "minimal-divider",
    density: "comprehensive",
    includeReferences: false,
    samplePrompt: "Incident post-mortem: timeline, root cause, contributing factors, action items.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "classic",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "centered",
    },
  },
  {
    id: "purple-keynote",
    name: "Purple Keynote",
    tagline: "Bold purple, silver accents. Conference keynotes.",
    category: "Keynote",
    themeId: "purple-white",
    fontId: "outfit",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Conference keynote on the future of work. The shift, the data, the new social contract.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "teal-pro",
    name: "Teal Professional",
    tagline: "Teal accents, crisp text. Healthcare and SaaS.",
    category: "Investor",
    themeId: "teal-white",
    fontId: "manrope",
    graphicId: "wave",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Series A pitch for a digital health platform. The problem, the model, traction, the team.",
    variants: {
      titleVariant: "asymmetric", bulletsVariant: "numbered", twoColumnVariant: "numbered",
      tableVariant: "accent-header", quoteVariant: "card", sectionVariant: "split",
      closingVariant: "contact",
    },
  },
  {
    id: "fog-product",
    name: "Fog Product",
    tagline: "Cool fog grays. Modern product reviews.",
    category: "Engineering",
    themeId: "fog",
    fontId: "plus-jakarta",
    graphicId: "soft-grid",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Quarterly product review. What we shipped, what users said, what's next on the roadmap.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "icon-check", twoColumnVariant: "compare",
      tableVariant: "zebra", quoteVariant: "card", sectionVariant: "minimal",
      closingVariant: "qa",
    },
  },
  {
    id: "slate-coral",
    name: "Slate & Coral",
    tagline: "Slate with coral pop. Brand strategy and creative pitches.",
    category: "Brand",
    themeId: "slate-coral",
    fontId: "outfit",
    graphicId: "corner-circles",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Brand strategy proposal. Positioning, voice, identity, the rollout.",
    variants: {
      titleVariant: "centered", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "charcoal-mono",
    name: "Charcoal Mono",
    tagline: "Charcoal with single-color discipline. Premium product launches.",
    category: "Keynote",
    themeId: "charcoal",
    fontId: "space-grotesk",
    graphicId: "concentric",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Launch deck for our flagship product. The moment, the why, the demo, the rollout.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "numbered", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "split",
      closingVariant: "cta",
    },
  },
  {
    id: "green-academic",
    name: "Green Academic",
    tagline: "Forest green serif. Lectures, theses, journal-style decks.",
    category: "Lecture",
    themeId: "green-white",
    fontId: "merriweather",
    graphicId: "minimal-divider",
    density: "comprehensive",
    includeReferences: true,
    samplePrompt: "Graduate thesis defense: motivation, related work, contributions, evaluation, future directions.",
    variants: {
      titleVariant: "centered", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "chapter",
      closingVariant: "qa",
    },
  },
  {
    id: "tangerine-event",
    name: "Tangerine Event",
    tagline: "High-energy tangerine. Event programs and festival decks.",
    category: "Marketing",
    themeId: "tangerine",
    fontId: "syne",
    graphicId: "ribbon-stripe",
    density: "concise",
    includeReferences: false,
    samplePrompt: "Festival program: the lineup, the venues, the schedule, sponsors, how to get there.",
    variants: {
      titleVariant: "big-initial", bulletsVariant: "cards", twoColumnVariant: "cards",
      tableVariant: "accent-header", quoteVariant: "stacked", sectionVariant: "kicker-hero",
      closingVariant: "cta",
    },
  },
  {
    id: "mint-friendly",
    name: "Mint Friendly",
    tagline: "Bright mint accents. HR, culture, internal communications.",
    category: "Training",
    themeId: "mint-sage",
    fontId: "figtree",
    graphicId: "dot-field",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "All-hands culture deck. Our values, behaviors we celebrate, how decisions get made.",
    variants: {
      titleVariant: "centered", bulletsVariant: "icon-check", twoColumnVariant: "cards",
      tableVariant: "minimal", quoteVariant: "card", sectionVariant: "kicker-hero",
      closingVariant: "qa",
    },
  },
  {
    id: "midnight-consulting",
    name: "Midnight Consulting",
    tagline: "A deep aurora-navy canvas with a soft mesh glow. Strategy, consulting, and board-level decks.",
    category: "Consulting",
    themeId: "aurora-night",
    fontId: "manrope",
    graphicId: "mesh-gradient",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Strategy review for the leadership team: the situation, key findings, our recommendation, the roadmap, and expected impact.",
    variants: {
      titleVariant: "stacked-bold", bulletsVariant: "chevron", twoColumnVariant: "compare",
      tableVariant: "accent-header", quoteVariant: "editorial", sectionVariant: "split",
      closingVariant: "cta",
    },
    isNew: true,
  },
  {
    id: "nordic-minimal",
    name: "Nordic Minimal",
    tagline: "Ultra-clean fog-grey with a whisper grid and underlined title. Calm, modern product storytelling.",
    category: "Product",
    themeId: "fog",
    fontId: "work-sans",
    graphicId: "soft-grid",
    density: "balanced",
    includeReferences: false,
    samplePrompt: "Product overview: the problem we solve, how it works, key features, results so far, and what's next.",
    variants: {
      titleVariant: "underlined", bulletsVariant: "dashed", twoColumnVariant: "divider",
      tableVariant: "minimal", quoteVariant: "centered", sectionVariant: "minimal",
      closingVariant: "contact",
    },
    isNew: true,
  },
  {
    id: "executive-slate",
    name: "Executive Slate",
    tagline: "Authoritative slate charcoal with an amber accent and bold corner blocks. Executive & board briefings.",
    category: "Executive",
    themeId: "slate-bold",
    fontId: "montserrat",
    graphicId: "corner-blocks",
    density: "detailed",
    includeReferences: true,
    samplePrompt: "Quarterly business review for the board: performance vs targets, wins and risks, financials, and priorities for next quarter.",
    variants: {
      titleVariant: "numbered", bulletsVariant: "numbered-cards", twoColumnVariant: "numbered",
      tableVariant: "bordered", quoteVariant: "card", sectionVariant: "panel",
      closingVariant: "signature",
    },
    isNew: true,
  },
];

/** Apply template variant defaults to a slide. Slide-level fields win, so
 *  AI-generated kicker/title/etc remain. The template only fills in
 *  variant slots that the slide hasn't already set. */
export function applyTemplateToSlide(slide: Slide, t: TemplateVariantDefaults): Slide {
  return {
    ...slide,
    titleVariant:    slide.titleVariant    ?? t.titleVariant,
    bulletsVariant:  slide.bulletsVariant  ?? t.bulletsVariant,
    twoColumnVariant:slide.twoColumnVariant?? t.twoColumnVariant,
    tableVariant:    slide.tableVariant    ?? t.tableVariant,
    quoteVariant:    slide.quoteVariant    ?? t.quoteVariant,
    sectionVariant:  slide.sectionVariant  ?? t.sectionVariant,
    closingVariant:  slide.closingVariant  ?? t.closingVariant,
  };
}

export function getTemplate(id?: string): DeckTemplate | undefined {
  return DECK_TEMPLATES.find((t) => t.id === id);
}
